"""Generate bounded blade geometry from the pinned official H3EK audit fixture."""
import argparse
import hashlib
import math
from pathlib import Path

PIN = 'e680fa2d554b27670d8549b1a04d88b9b3be5da67f80483cf2da838364c08302'


def generate(source):
    raw = source.read_bytes()
    if hashlib.sha256(raw).hexdigest() != PIN:
        raise ValueError('Fixture differs from the documented official H3EK export audit')
    rows = raw.decode('ascii').splitlines()
    assert int(rows[0]) == len(rows) - 1 == 244
    sides = [[], []]
    for row in rows[1:]:
        values = list(map(float, row.split()))
        assert len(values) == 9 and all(math.isfinite(v) for v in values)
        face = [tuple(values[i:i+3]) for i in (0, 3, 6)]
        if all(p[1] > 0 for p in face):
            sides[0].append(face)
        elif all(p[1] < 0 for p in face):
            sides[1].append(face)
        else:
            raise ValueError('A face crosses the authored gap')
    points, faces = [], []
    for side in sides:
        assert len(side) == 122
        unique = list(dict.fromkeys(p for face in side for p in face))
        assert len(unique) == 63
        lookup = {p: len(points) + i for i, p in enumerate(unique)}
        faces.extend(tuple(lookup[p] for p in face) for face in side)
        points.extend(unique)
    def f(v):
        s = format(v, '.9g')
        return s + ('.0f' if '.' not in s and 'e' not in s else 'f')
    return '\n'.join([
        '// Generated by tools/generate-h3-sword-geometry.py; do not hand-edit.',
        '// Official H3EK provenance: docs/HALO3-SWORD-CONTACT-EVIDENCE.md.',
        '// Audited fixture SHA-256: ' + PIN,
        '#pragma once',
        '#include "physical_contact_logic.h"',
        'inline constexpr PhysicalContactVec3 kHalo3SwordBladePoints[126] = {',
        *('    {' + ', '.join(map(f, p)) + '},' for p in points),
        '};',
        'inline constexpr uint16_t kHalo3SwordBladeFaces[244][3] = {',
        *('    {' + ', '.join(map(str, face)) + '},' for face in faces),
        '};', '',
    ])


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('fixture', type=Path)
    parser.add_argument('output', type=Path)
    args = parser.parse_args()
    args.output.write_text(generate(args.fixture), encoding='ascii', newline='\n')
